---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-ingress-deny-all
  namespace: {{ .Release.Name }}
  labels:
    ns: {{ .Release.Name }}
    team: {{ splitList "-" .Release.Name | initial | join "-" | upper }}
    environment: {{ splitList "-" .Release.Name | last }}
spec:
  podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-ingress-allow-ns
  namespace: {{ .Release.Name }}
  labels:
    ns: {{ .Release.Name }}
    team: {{ splitList "-" .Release.Name | initial | join "-" | upper }}
    environment: {{ splitList "-" .Release.Name | last }}
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-ingress-allow-kube-system
  namespace: {{ .Release.Name }}
  labels:
    ns: {{ .Release.Name }}
    team: {{ splitList "-" .Release.Name | initial | join "-" | upper }}
    environment: {{ splitList "-" .Release.Name | last }}
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          ns: kube-system
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress-deny-all
  namespace: {{ .Release.Name }}
  labels:
    ns: {{ .Release.Name }}
    team: {{ splitList "-" .Release.Name | initial | join "-" | upper }}
    environment: {{ splitList "-" .Release.Name | last }}
spec:
  policyTypes:
  - Egress
  podSelector: {}
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress-allow-dns
  namespace: {{ .Release.Name }}
  labels:
    ns: {{ .Release.Name }}
    team: {{ splitList "-" .Release.Name | initial | join "-" | upper }}
    environment: {{ splitList "-" .Release.Name | last }}
spec:
  policyTypes:
  - Egress
  podSelector: {}
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
         ns: kube-system
