apiVersion: v2
name: namespace
description: This chart creates a new isolated namespace
version: 1.0.0
kubeVersion: ">= 1.16.0 < 1.18.0"
maintainers:
- name: Amir Heinisch
  email: mail@amir-heinisch.de
