apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    ns: {{ .Release.Namespace }}
    app: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
